apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: taskmanager-app-vpa
  namespace: devsecops
spec:
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: taskmanager-app
  updatePolicy:
    updateMode: "Off"
