apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: "2026-07-20T12:40:18Z"
  labels:
    kubernetes.io/metadata.name: ingress-nginx
    name: ingress-nginx
  name: ingress-nginx
  resourceVersion: "12056"
  uid: 6f6c02d5-9e39-4115-91c9-1fb41193b905
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
