apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanager-app
  namespace: devsecops
  labels:
    app: taskmanager-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: taskmanager-app
  template:
    metadata:
      labels:
        app: taskmanager-app
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: taskmanager-app
          image: riahiamani/taskmanager-flask:latest
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 5000
          envFrom:
            - secretRef:
                name: taskmanager-app-secret
          resources:
            requests:
              memory: "180Mi"
              cpu: "150m"
            limits:
              memory: "384Mi"
              cpu: "500m"
          readinessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            tcpSocket:
              port: 5000
            initialDelaySeconds: 15
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: taskmanager-app-service
  namespace: devsecops
  labels:
    app: taskmanager-app
spec:
  selector:
    app: taskmanager-app
  ports:
  - name: http
    port: 80
    targetPort: 5000
