apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: taskmanager-postgres-pvc
  namespace: devsecops
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanager-postgres
  namespace: devsecops
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: taskmanager-postgres
  template:
    metadata:
      labels:
        app: taskmanager-postgres
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 999
        runAsGroup: 999
        fsGroup: 999
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: postgres
          image: postgres:16
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef:
                name: taskmanager-postgres-secret
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: taskmanager-postgres-pvc
