prometheus-node-exporter:
  extraArgs:
    - --collector.textfile.directory=/host/textfile
  extraHostVolumeMounts:
    - name: textfile
      hostPath: /var/lib/node-exporter/textfile
      mountPath: /host/textfile
      readOnly: true
      mountPropagation: HostToContainer
