apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: taskmanager-ingress
  namespace: devsecops
spec:
  ingressClassName: nginx
  rules:
  - host: taskmanager.riahi.dpdns.org
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: taskmanager-app-service
            port:
              number: 80
